FROM debian:buster

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y wget php7.3 php-fpm php-mysql mariadb-client vim
RUN echo ":syntax on\n:set number\n:set tabstop=4\n:set shiftwidth=4\n:set expandtab" > /root/.vimrc

RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && rm wordpress-6.0-fr_FR.tar.gz
RUN chown -R root:root /var/www/wordpress
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY conf/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
COPY conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm7.3", "-F"]
